/* SQL Manager Lite for InterBase and Firebird 5.3.0.46603 */
/* ------------------------------------------------------- */
/* Host     : embedded                                     */
/* Database : F:\Adem\Desktop\bt_envanter\data\BT          */


CREATE DATABASE 'F:\Adem\Desktop\bt_envanter\data\BT'   USER 'SYSDBA'
   PAGE_SIZE 8192
   DEFAULT CHARACTER SET WIN1254;

/* Structure for the `KULLANICI` table :  */

CREATE TABLE KULLANICI (
  ID BIGINT NOT NULL,
  ADI VARCHAR(50) NOT NULL,
  SOYADI VARCHAR(50) NOT NULL,
  BIRIM VARCHAR(20),
  TELEFON_DAHILI VARCHAR(20),
  TELEFON_GSM VARCHAR(20),
  KAYIT_TARIHI TIMESTAMP NOT NULL);


ALTER TABLE KULLANICI ADD CONSTRAINT PK_KULLANICI PRIMARY KEY (ID);

/* Structure for the `ENVANTER` table :  */

CREATE TABLE ENVANTER (
  ID BIGINT NOT NULL,
  TIPI VARCHAR(20) NOT NULL,
  ACIKLAMA VARCHAR(200),
  KAYIT_TARIHI TIMESTAMP NOT NULL,
  KULLANICI_ID BIGINT,
  YERI VARCHAR(200),
  BIRIM VARCHAR(200),
  DURUM VARCHAR(200),
  MARKA VARCHAR(200),
  MODEL VARCHAR(200));


ALTER TABLE ENVANTER ADD CONSTRAINT PK_ENVANTER PRIMARY KEY (ID);

ALTER TABLE ENVANTER ADD CONSTRAINT FK_ENVANTER_KULLANICI FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICI(ID) ON DELETE SET NULL;

/* Structure for the `ENVANTER_BILGI` table :  */

CREATE TABLE ENVANTER_BILGI (
  ID BIGINT NOT NULL,
  TIPI VARCHAR(200) NOT NULL,
  DEGER1 VARCHAR(200) NOT NULL,
  DEGER2 VARCHAR(200),
  DEGER3 VARCHAR(200),
  ENVANTER_ID BIGINT NOT NULL,
  KAYIT_TARIHI TIMESTAMP NOT NULL,
  ACIKLAMA VARCHAR(200));


ALTER TABLE ENVANTER_BILGI ADD CONSTRAINT PK_ENVANTER_BILGI PRIMARY KEY (ID);

ALTER TABLE ENVANTER_BILGI ADD CONSTRAINT FK_ENVANTER_BILGI FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER(ID) ON DELETE CASCADE;

/* Definition for the `SP_ENVANTER_BILGI_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_ENVANTER_BILGI_EKLE(
  PI_TIPI VARCHAR(200),
  PI_DEGER1 VARCHAR(200),
  PI_DEGER2 VARCHAR(200),
  PI_DEGER3 VARCHAR(200),
  PI_ENVANTER_ID BIGINT)
AS
BEGIN
  /* Procedure body */
  INSERT INTO ENVANTER_BILGI (TIPI,DEGER1,DEGER2,DEGER3,ENVANTER_ID)
  VALUES (:PI_TIPI,:PI_DEGER1,:PI_DEGER2,:PI_DEGER3,:PI_ENVANTER_ID);
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_ENVANTER_BILGI_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_ENVANTER_BILGI_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM ENVANTER_BILGI WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_ENVANTER_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_ENVANTER_EKLE(
  PI_TIPI VARCHAR(20) NOT NULL,
  PI_ACIKLAMA VARCHAR(200))
AS
BEGIN
  /* Procedure body */
  INSERT INTO ENVANTER (TIPI,ACIKLAMA)
  VALUES (:PI_TIPI,:PI_ACIKLAMA);
  SUSPEND;
END^

SET TERM ; ^

/* Structure for the `ENVANTER_GIRIS_BILGI` table :  */

CREATE TABLE ENVANTER_GIRIS_BILGI (
  ID BIGINT NOT NULL,
  TIPI VARCHAR(200) NOT NULL,
  KULLANICI_ADI VARCHAR(200),
  SIFRE VARCHAR(200) CHARACTER SET NONE,
  ACIKLAMA VARCHAR(200),
  KAYIT_TARIHI TIMESTAMP NOT NULL,
  ENVANTER_ID BIGINT NOT NULL);


ALTER TABLE ENVANTER_GIRIS_BILGI ADD CONSTRAINT PK_ENVANTER_GIRIS_BILGI PRIMARY KEY (ID);

ALTER TABLE ENVANTER_GIRIS_BILGI ADD CONSTRAINT FK_ENVANTER_GIRIS_BILGI FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER(ID) ON DELETE CASCADE;

/* Definition for the `SP_ENVANTER_GIRIS_BILGI_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_ENVANTER_GIRIS_BILGI_EKLE(
  PI_TIPI VARCHAR(50),
  PI_KULLANICI_ADI VARCHAR(50),
  PI_SIFRE VARCHAR(50),
  PI_ACIKLAMA VARCHAR(200),
  PI_ENVANTER_ID BIGINT)
AS
BEGIN
  /* Procedure body */
  INSERT INTO ENVANTER_GIRIS_BILGI (TIPI,KULLANICI_ADI,SIFRE,ACIKLAMA,ENVANTER_ID)
  VALUES (:PI_TIPI,:PI_KULLANICI_ADI,:PI_SIFRE,:PI_ACIKLAMA,:PI_ENVANTER_ID);
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_ENVANTER_GIRIS_BILGI_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_ENVANTER_GIRIS_BILGI_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM ENVANTER_GIRIS_BILGI WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_ENVANTER_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_ENVANTER_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM ENVANTER WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Structure for the `KULLANICI_BILGI` table :  */

CREATE TABLE KULLANICI_BILGI (
  ID BIGINT NOT NULL,
  TIPI VARCHAR(200) NOT NULL,
  DEGER1 VARCHAR(200) NOT NULL,
  DEGER2 VARCHAR(200),
  DEGER3 VARCHAR(200),
  KULLANICI_ID BIGINT NOT NULL,
  KAYIT_TARIHI TIMESTAMP NOT NULL,
  ACIKLAMA VARCHAR(200));


ALTER TABLE KULLANICI_BILGI ADD CONSTRAINT PK_KULLANICI_BILGI PRIMARY KEY (ID);

ALTER TABLE KULLANICI_BILGI ADD CONSTRAINT FK_KULLANICI_BILGI FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICI(ID) ON DELETE CASCADE;

/* Definition for the `SP_KULLANICI_BILGI_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_KULLANICI_BILGI_EKLE(
  PI_TIPI VARCHAR(200) NOT NULL,
  PI_DEGER1 VARCHAR(200) NOT NULL,
  PI_DEGER2 VARCHAR(200),
  PI_DEGER3 VARCHAR(200),
  PI_KULLANICI_ID BIGINT)
AS
BEGIN
  /* Procedure body */
  INSERT INTO KULLANICI_BILGI (TIPI,DEGER1,DEGER2,DEGER3,KULLANICI_ID)
  VALUES (:PI_TIPI,:PI_DEGER1,:PI_DEGER2,:PI_DEGER3,:PI_KULLANICI_ID);
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_KULLANICI_BILGI_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_KULLANICI_BILGI_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM KULLANICI_BILGI WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_KULLANICI_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_KULLANICI_EKLE(
  PI_ADI VARCHAR(50) NOT NULL,
  PI_SOYADI VARCHAR(50) NOT NULL,
  PI_BIRIM VARCHAR(20),
  PI_TELEFON_DAHILI VARCHAR(20),
  PI_TELEFON_GSM VARCHAR(20))
AS
BEGIN
  /* Procedure body */
  INSERT INTO KULLANICI (ADI,SOYADI,BIRIM,TELEFON_DAHILI,TELEFON_GSM)
  VALUES (:PI_ADI,:PI_SOYADI,:PI_BIRIM,:PI_TELEFON_DAHILI,:PI_TELEFON_GSM);
  SUSPEND;
END^

SET TERM ; ^

/* Structure for the `KULLANICI_GIRIS_BILGI` table :  */

CREATE TABLE KULLANICI_GIRIS_BILGI (
  ID BIGINT NOT NULL,
  TIPI VARCHAR(200),
  KULLANICI_ADI VARCHAR(200) NOT NULL,
  SIFRE VARCHAR(200) NOT NULL,
  ACIKLAMA VARCHAR(200),
  ENVANTER_ID BIGINT,
  KULLANICI_ID BIGINT NOT NULL,
  KAYIT_TARIHI TIMESTAMP NOT NULL);


ALTER TABLE KULLANICI_GIRIS_BILGI ADD CONSTRAINT PK_KULLANICI_GIRIS_BILGI PRIMARY KEY (ID);

ALTER TABLE KULLANICI_GIRIS_BILGI ADD CONSTRAINT FK_KULLANICI_GIRIS_BILGI FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICI(ID) ON DELETE CASCADE;

ALTER TABLE KULLANICI_GIRIS_BILGI ADD CONSTRAINT FK_KULLANICI_GIRIS_ENVANTER FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER(ID);

/* Definition for the `SP_KULLANICI_GIRIS_BILGI_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_KULLANICI_GIRIS_BILGI_EKLE(
  PI_TIPI VARCHAR(200) NOT NULL,
  PI_KULLANICI_ADI VARCHAR(200) NOT NULL,
  PI_SIFRE VARCHAR(200),
  PI_ACIKLAMA VARCHAR(200),
  PI_ENVANTER_ID BIGINT,
  PI_KULLANICI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  INSERT INTO KULLANICI_GIRIS_BILGI (TIPI,KULLANICI_ADI,SIFRE,ACIKLAMA,ENVANTER_ID,KULLANICI_ID)
  VALUES (:PI_TIPI,:PI_KULLANICI_ADI,:PI_SIFRE,:PI_ACIKLAMA,:PI_ENVANTER_ID,:PI_KULLANICI_ID);
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_KULLANICI_GIRIS_BILGI_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_KULLANICI_GIRIS_BILGI_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM KULLANICI_GIRIS_BILGI WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_KULLANICI_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_KULLANICI_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM KULLANICI WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Structure for the `LISANS` table :  */

CREATE TABLE LISANS (
  ID BIGINT NOT NULL,
  TIPI VARCHAR(200) NOT NULL,
  BASLANGIC_TARIHI DATE,
  BITIS_TARIHI DATE,
  ACIKLAMA VARCHAR(200),
  ENVANTER_ID BIGINT,
  KAYIT_TARIHI TIMESTAMP NOT NULL);


ALTER TABLE LISANS ADD CONSTRAINT PK_LISANS PRIMARY KEY (ID);

ALTER TABLE LISANS ADD CONSTRAINT FK_LISANS_ENVANTER FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER(ID) ON DELETE CASCADE;

/* Structure for the `LISANS_BILGI` table :  */

CREATE TABLE LISANS_BILGI (
  ID BIGINT NOT NULL,
  TIPI VARCHAR(200) NOT NULL,
  DEGER1 VARCHAR(200) NOT NULL,
  DEGER2 VARCHAR(200),
  DEGER3 VARCHAR(200),
  LISANS_ID BIGINT NOT NULL,
  KAYIT_TARIHI TIMESTAMP NOT NULL,
  ACIKLAMA VARCHAR(200));


ALTER TABLE LISANS_BILGI ADD CONSTRAINT PK_LISANS_BILGI PRIMARY KEY (ID);

ALTER TABLE LISANS_BILGI ADD CONSTRAINT FK_LISANS_BILGI FOREIGN KEY (LISANS_ID) REFERENCES LISANS(ID) ON DELETE CASCADE;

/* Definition for the `SP_LISANS_BILGI_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_LISANS_BILGI_EKLE(
  PI_TIPI VARCHAR(200) NOT NULL,
  PI_DEGER1 VARCHAR(200) NOT NULL,
  PI_DEGER2 VARCHAR(200),
  PI_DEGER3 VARCHAR(200),
  PI_LISANS_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  INSERT INTO LISANS_BILGI (TIPI,DEGER1,DEGER2,DEGER3,LISANS_ID)
  VALUES (:PI_TIPI,:PI_DEGER1,:PI_DEGER2,:PI_DEGER3,:PI_LISANS_ID);
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_LISANS_BILGI_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_LISANS_BILGI_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM LISANS_BILGI WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_LISANS_EKLE` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_LISANS_EKLE(
  PI_TIPI VARCHAR(200) NOT NULL,
  PI_BASLANGIC_TARIHI DATE,
  PI_BITIS_TARIHI DATE,
  PI_ACIKLAMA VARCHAR(200),
  PI_ENVANTER_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  INSERT INTO LISANS (TIPI,BASLANGIC_TARIHI,BITIS_TARIHI,ACIKLAMA,ENVANTER_ID)
  VALUES (:PI_TIPI,:PI_BASLANGIC_TARIHI,:PI_BITIS_TARIHI,:PI_ACIKLAMA,:PI_ENVANTER_ID);
  SUSPEND;
END^

SET TERM ; ^

/* Definition for the `SP_LISANS_SIL` procedure :  */

SET TERM ^ ;

CREATE PROCEDURE SP_LISANS_SIL(
  PI_ID BIGINT NOT NULL)
AS
BEGIN
  /* Procedure body */
  DELETE FROM LISANS WHERE ID=:PI_ID;
  SUSPEND;
END^

SET TERM ; ^

/* Structure for the `ENVANTER_BILGI_BOS_ID` table :  */

CREATE TABLE ENVANTER_BILGI_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_ENVANTER_BILGI_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_ENVANTER_BILGI_SIL FOR ENVANTER_BILGI
ACTIVE AFTER DELETE
POSITION 0
AS
BEGIN
  /* Trigger body */
  INSERT INTO ENVANTER_BILGI_BOS_ID (BOS_ID) VALUES (OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_ENVANTER_BILGI_ID` generator :  */

CREATE GENERATOR GEN_ENVANTER_BILGI_ID;

SET GENERATOR GEN_ENVANTER_BILGI_ID TO 3;

/* Definition for the `TRG_ENVANTER_BILGI_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_ENVANTER_BILGI_YENI FOR ENVANTER_BILGI
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM ENVANTER_BILGI_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM ENVANTER_BILGI_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM ENVANTER_BILGI_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_ENVANTER_BILGI_ID, 1);
   	END 
END^

SET TERM ; ^

/* Structure for the `ENVANTER_GIRIS_BILGI_BOS_ID` table :  */

CREATE TABLE ENVANTER_GIRIS_BILGI_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_ENVANTER_GIRIS_BILGI_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_ENVANTER_GIRIS_BILGI_SIL FOR ENVANTER_GIRIS_BILGI
ACTIVE AFTER DELETE
POSITION 0
AS
BEGIN
  /* Trigger body */
  INSERT INTO ENVANTER_GIRIS_BILGI_BOS_ID (BOS_ID) VALUES (OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_ENVANTER_GIRIS_BILGI_ID` generator :  */

CREATE GENERATOR GEN_ENVANTER_GIRIS_BILGI_ID;

SET GENERATOR GEN_ENVANTER_GIRIS_BILGI_ID TO 3;

/* Definition for the `TRG_ENVANTER_GIRIS_BILGI_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_ENVANTER_GIRIS_BILGI_YENI FOR ENVANTER_GIRIS_BILGI
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM ENVANTER_GIRIS_BILGI_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM ENVANTER_GIRIS_BILGI_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM ENVANTER_GIRIS_BILGI_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_ENVANTER_GIRIS_BILGI_ID, 1);
   	END 
END^

SET TERM ; ^

/* Structure for the `ENVANTER_BOS_ID` table :  */

CREATE TABLE ENVANTER_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_ENVANTER_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_ENVANTER_SIL FOR ENVANTER
ACTIVE AFTER DELETE
POSITION 0
AS
BEGIN
  /* Trigger body */
  INSERT INTO ENVANTER_BOS_ID (BOS_ID) VALUES (OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_ENVANTER_ID` generator :  */

CREATE GENERATOR GEN_ENVANTER_ID;

SET GENERATOR GEN_ENVANTER_ID TO 5;

/* Definition for the `TRG_ENVANTER_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_ENVANTER_YENI FOR ENVANTER
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM ENVANTER_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM ENVANTER_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM ENVANTER_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_ENVANTER_ID, 1);
   	END 
END^

SET TERM ; ^

/* Structure for the `KULLANICI_BILGI_BOS_ID` table :  */

CREATE TABLE KULLANICI_BILGI_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_KULLANICI_BILGI_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_KULLANICI_BILGI_SIL FOR KULLANICI_BILGI
ACTIVE AFTER DELETE
POSITION 0
AS
BEGIN
  /* Trigger body */
  INSERT INTO KULLANICI_BILGI_BOS_ID (BOS_ID) VALUES (OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_KULLANICI_BILGI_ID` generator :  */

CREATE GENERATOR GEN_KULLANICI_BILGI_ID;

SET GENERATOR GEN_KULLANICI_BILGI_ID TO 9;

/* Definition for the `TRG_KULLANICI_BILGI_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_KULLANICI_BILGI_YENI FOR KULLANICI_BILGI
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM KULLANICI_BILGI_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM KULLANICI_BILGI_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM KULLANICI_BILGI_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_KULLANICI_BILGI_ID, 1);
   	END 
END^

SET TERM ; ^

/* Definition for the `TRG_KULLANICI_GIRIS_BILGI_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_KULLANICI_GIRIS_BILGI_SIL FOR KULLANICI_GIRIS_BILGI
ACTIVE AFTER DELETE
POSITION 0
AS
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
  /* Trigger body */
  INSERT INTO KULLANICI_BILGI_BOS_ID (BOS_ID) VALUES (OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_KULLANICI_GIRIS_BILGI_ID` generator :  */

CREATE GENERATOR GEN_KULLANICI_GIRIS_BILGI_ID;

SET GENERATOR GEN_KULLANICI_GIRIS_BILGI_ID TO 6;

/* Structure for the `KULLANICI_GIRIS_BILGI_BOS_ID` table :  */

CREATE TABLE KULLANICI_GIRIS_BILGI_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_KULLANICI_GIRIS_BILGI_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_KULLANICI_GIRIS_BILGI_YENI FOR KULLANICI_GIRIS_BILGI
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM KULLANICI_GIRIS_BILGI_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM KULLANICI_GIRIS_BILGI_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM KULLANICI_GIRIS_BILGI_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_KULLANICI_GIRIS_BILGI_ID, 1);
   	END 
END^

SET TERM ; ^

/* Structure for the `KULLANICI_BOS_ID` table :  */

CREATE TABLE KULLANICI_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_KULLANICI_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_KULLANICI_SIL FOR KULLANICI
ACTIVE AFTER DELETE
POSITION 0
AS
BEGIN
  /* Trigger body */
  INSERT INTO KULLANICI_BOS_ID (BOS_ID) VALUES (OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_KULLANICI_ID` generator :  */

CREATE GENERATOR GEN_KULLANICI_ID;

SET GENERATOR GEN_KULLANICI_ID TO 6;

/* Definition for the `TRG_KULLANICI_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_KULLANICI_YENI FOR KULLANICI
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM KULLANICI_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM KULLANICI_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM KULLANICI_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_KULLANICI_ID, 1);
   	END 
END^

SET TERM ; ^

/* Structure for the `LISANS_BILGI_BOS_ID` table :  */

CREATE TABLE LISANS_BILGI_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_LISANS_BILGI_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_LISANS_BILGI_SIL FOR LISANS_BILGI
ACTIVE AFTER DELETE
POSITION 0
AS
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
  /* Trigger body */
  INSERT INTO LISANS_BILGI_BOS_ID (BOS_ID) VALUES(OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_LISANS_BILGI_ID` generator :  */

CREATE GENERATOR GEN_LISANS_BILGI_ID;

SET GENERATOR GEN_LISANS_BILGI_ID TO 4;

/* Definition for the `TRG_LISANS_BILGI_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_LISANS_BILGI_YENI FOR LISANS_BILGI
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM LISANS_BILGI_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM LISANS_BILGI_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM LISANS_BILGI_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_LISANS_BILGI_ID, 1);
   	END 
END^

SET TERM ; ^

/* Structure for the `LISANS_BOS_ID` table :  */

CREATE TABLE LISANS_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_LISANS_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_LISANS_SIL FOR LISANS
ACTIVE AFTER DELETE
POSITION 0
AS
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
  /* Trigger body */
  INSERT INTO LISANS_BOS_ID (BOS_ID) VALUES(OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_LISANS_ID` generator :  */

CREATE GENERATOR GEN_LISANS_ID;

SET GENERATOR GEN_LISANS_ID TO 2;

/* Definition for the `TRG_LISANS_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_LISANS_YENI FOR LISANS
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM LISANS_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM LISANS_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM LISANS_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_LISANS_ID, 1);
   	END 
END^

SET TERM ; ^

/* Definition for the `VIEW_ENVANTER_BILGI_TIPI` view :  */

CREATE VIEW VIEW_ENVANTER_BILGI_TIPI(
  ENVANTER_BILGI_TIPI)
AS
SELECT DISTINCT(TIPI) FROM ENVANTER_BILGI;

/* Definition for the `VIEW_ENVANTER_BIRIM` view :  */

CREATE VIEW VIEW_ENVANTER_BIRIM(
  ENVANTER_BIRIM)
AS
SELECT DISTINCT(BIRIM) FROM ENVANTER;

/* Definition for the `VIEW_ENVANTER_GIRIS_BILGI_TIPI` view :  */

CREATE VIEW VIEW_ENVANTER_GIRIS_BILGI_TIPI(
  ENVANTER_GIRIS_BILGI_TIPI)
AS
SELECT DISTINCT(TIPI) FROM ENVANTER_GIRIS_BILGI;

/* Definition for the `VIEW_ENVANTER_TIPI` view :  */

CREATE VIEW VIEW_ENVANTER_TIPI(
  ENVANTER_TIPI)
AS
SELECT DISTINCT(TIPI) FROM ENVANTER;

/* Definition for the `VIEW_KULLANICI_BILGI_TIPI` view :  */

CREATE VIEW VIEW_KULLANICI_BILGI_TIPI(
  KULLANICI_BILGI_TIPI)
AS
SELECT DISTINCT(TIPI) FROM KULLANICI_BILGI;

/* Definition for the `VIEW_KULLANICI_BIRIM` view :  */

CREATE VIEW VIEW_KULLANICI_BIRIM(
  KULLANICI_BIRIM)
AS
SELECT DISTINCT(BIRIM) FROM KULLANICI;

/* Definition for the `VIEW_KULLANICI_GIRIS_BILGI_TIPI` view :  */

CREATE VIEW VIEW_KULLANICI_GIRIS_BILGI_TIPI(
  KULLANICI_GIRIS_BILGI_TIPI)
AS
SELECT DISTINCT(TIPI) FROM KULLANICI_GIRIS_BILGI;

/* Definition for the `VIEW_LISANS_BILGI_TIPI` view :  */

CREATE VIEW VIEW_LISANS_BILGI_TIPI(
  LISANS_BILGI_TIPI)
AS
SELECT DISTINCT(TIPI) FROM LISANS_BILGI;

/* Definition for the `VIEW_LISANS_TIPI` view :  */

CREATE VIEW VIEW_LISANS_TIPI(
  LISANS_TIPI)
AS
SELECT DISTINCT(TIPI) FROM LISANS;

/* Structure for the `AYARLAR` table :  */

CREATE TABLE AYARLAR (
  AYAR VARCHAR(200) NOT NULL,
  DEGER1 VARCHAR(200) NOT NULL,
  DEGER2 VARCHAR(200),
  DEGER3 VARCHAR(200),
  KAYIT_TARIHI TIMESTAMP NOT NULL,
  ID BIGINT NOT NULL);


ALTER TABLE AYARLAR ADD PRIMARY KEY (ID) USING INDEX RDB$PRIMARY3;

/* Definition for the `GEN_AYARLAR_ID` generator :  */

CREATE GENERATOR GEN_AYARLAR_ID;

/* Definition for the `TRG_AYARLAR_ID` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_AYARLAR_ID FOR AYARLAR
ACTIVE BEFORE INSERT
POSITION 0
AS
BEGIN
  IF (NEW.ID IS NULL) THEN
      NEW.ID = GEN_ID(GEN_AYARLAR_ID, 1);
END^

SET TERM ; ^

/* Structure for the `GIRIS` table :  */

CREATE TABLE GIRIS (
  ID BIGINT NOT NULL,
  KULLANICI_ADI VARCHAR(200) NOT NULL,
  SIFRE VARCHAR(200) NOT NULL,
  KAYIT_TARIHI TIMESTAMP NOT NULL);


ALTER TABLE GIRIS ADD PRIMARY KEY (ID) USING INDEX RDB$PRIMARY2;

/* Structure for the `GIRIS_BOS_ID` table :  */

CREATE TABLE GIRIS_BOS_ID (
  BOS_ID BIGINT NOT NULL);

/* Definition for the `TRG_GIRIS_SIL` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_GIRIS_SIL FOR GIRIS
ACTIVE AFTER DELETE
POSITION 0
AS
BEGIN
  /* Trigger body */
  INSERT INTO GIRIS_BOS_ID (BOS_ID) VALUES (OLD.ID);
END^

SET TERM ; ^

/* Definition for the `GEN_GIRIS_ID` generator :  */

CREATE GENERATOR GEN_GIRIS_ID;

/* Definition for the `TRG_GIRIS_YENI` trigger :  */

SET TERM ^ ;

CREATE TRIGGER TRG_GIRIS_YENI FOR GIRIS
ACTIVE BEFORE INSERT
POSITION 0
AS
DECLARE VARIABLE BOSID BIGINT NOT NULL;
DECLARE VARIABLE BOSCOUNT BIGINT NOT NULL;
DECLARE VARIABLE TARIH TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP;
BEGIN
	NEW.KAYIT_TARIHI=TARIH;
	SELECT COUNT(*) FROM GIRIS_BOS_ID INTO :BOSCOUNT;
    IF(BOSCOUNT<>0)THEN
    BEGIN
		SELECT FIRST 1 SKIP 0 BOS_ID FROM GIRIS_BOS_ID ORDER BY BOS_ID ASC INTO :BOSID;
        NEW.ID=:BOSID;
    	DELETE FROM GIRIS_BOS_ID WHERE BOS_ID=:BOSID;
   	END
   	ELSE
   	BEGIN
   		/*IF (NEW.ID IS NULL) THEN*/
  		NEW.ID = GEN_ID(GEN_GIRIS_ID, 1);
   	END 
END^

SET TERM ; ^

/* Data for the `KULLANICI` table  (Records 1 - 5) */

INSERT INTO KULLANICI
VALUES (2, 'ALÝ', 'VELÝ', 'SATINALMA', '12332', '12123', '2016-11-07 00:36:09');

INSERT INTO KULLANICI
VALUES (3, 'GGGG', 'GGG', 'D', 'GGG', 'GGGG', '2016-11-08 13:14:48');

INSERT INTO KULLANICI
VALUES (1, 'D', 'D', 'D', 'D', 'D', '2016-10-29 00:42:51');

INSERT INTO KULLANICI
VALUES (4, 'asdasd', 'asdas', 'asdasd', 'asdasd', 'asdasd', '2016-11-08 14:18:56');

INSERT INTO KULLANICI
VALUES (6, 'A', 'B', 'F', 'C', 'D', '2016-11-04 22:48:11');

COMMIT WORK;

/* Data for the `ENVANTER` table  (Records 1 - 5) */

INSERT INTO ENVANTER
VALUES (1, 'MODEM', 'INTERNET', '2016-11-09 00:15:30', NULL, 'BÝLGÝ ÝÞLEM', 'BÝLGÝ ÝÞLEM', NULL, NULL, NULL);

INSERT INTO ENVANTER
VALUES (2, 'ACCESS POINT', NULL, '2016-11-09 00:16:11', NULL, 'SEVKÝYAT', 'SEVKÝYAT', 'KULLANILIYOR', 'AIRTIES', 'RT-205');

INSERT INTO ENVANTER
VALUES (4, 'ANAKART', NULL, '2016-11-11 20:22:29', NULL, 'BÝLGÝÞLEM', 'BÝLGÝ ÝÞLEM', 'ÇALIÞIYOR', 'ASUS', 'P5KPLAM-SE');

INSERT INTO ENVANTER
VALUES (3, 'BÝLGÝSAYAR', NULL, '2016-11-09 03:22:49', 2, 'SATINALMA', 'SATINALMA', 'ÇALIÞIYOR', 'MSI', 'VR 600');

INSERT INTO ENVANTER
VALUES (5, 'KABLOSUZ SET', NULL, '2016-11-11 20:23:35', NULL, 'SEVKÝYAT', 'SATINALMA', NULL, 'MICROSOFT', '1T-55');

COMMIT WORK;

/* Data for the `ENVANTER_BILGI` table  (Records 1 - 2) */

INSERT INTO ENVANTER_BILGI
VALUES (2, 'HDD', '1 TB', NULL, NULL, 3, '2016-11-09 22:24:34', 'SEAGATE SATA3 7200RPM');

INSERT INTO ENVANTER_BILGI
VALUES (3, 'ÝÞLEMCÝ', '3.20GHZ', NULL, NULL, 3, '2016-11-09 22:25:50', 'INTEL i5');

COMMIT WORK;

/* Data for the `ENVANTER_GIRIS_BILGI` table  (Records 1 - 3) */

INSERT INTO ENVANTER_GIRIS_BILGI
VALUES (2, 'ARAYÜZ', 'admin', 'admin', NULL, '2016-11-11 20:07:51', 2);

INSERT INTO ENVANTER_GIRIS_BILGI
VALUES (3, 'KABLOSUZ', 'SEVKIYAT', 'abc.123', NULL, '2016-11-11 20:09:16', 2);

INSERT INTO ENVANTER_GIRIS_BILGI
VALUES (1, 'ARAYÜZ', 'admin', '123456', NULL, '2016-11-12 04:04:14', 1);

COMMIT WORK;

/* Data for the `KULLANICI_BILGI` table  (Records 1 - 7) */

INSERT INTO KULLANICI_BILGI
VALUES (2, 'B', 'B', 'B', 'B', 1, '2016-10-29 13:44:20', NULL);

INSERT INTO KULLANICI_BILGI
VALUES (1, 'IP', '192.168.10.12', '', '', 2, '2016-11-07 00:36:33', NULL);

INSERT INTO KULLANICI_BILGI
VALUES (3, 'IP', '123123123', '', '', 3, '2016-11-08 14:19:14', NULL);

INSERT INTO KULLANICI_BILGI
VALUES (7, 'E', 'E', 'E', 'E', 1, '2016-11-04 16:56:16', NULL);

INSERT INTO KULLANICI_BILGI
VALUES (5, 'A', 'A', 'A', 'A', 1, '2016-10-29 14:04:40', NULL);

INSERT INTO KULLANICI_BILGI
VALUES (8, 'IP', '192.168.10.1', '', '', 1, '2016-11-04 16:56:28', NULL);

INSERT INTO KULLANICI_BILGI
VALUES (9, 'IP', '192.168.10.2', '', '', 1, '2016-11-04 16:56:45', NULL);

COMMIT WORK;

/* Data for the `KULLANICI_GIRIS_BILGI` table  (Records 1 - 5) */

INSERT INTO KULLANICI_GIRIS_BILGI
VALUES (1, 'ACTIVE DIRECTORY', 'ASD', 'ASD', '', NULL, 2, '2016-11-07 00:36:56');

INSERT INTO KULLANICI_GIRIS_BILGI
VALUES (3, 'C', 'C', 'C', 'C', NULL, 1, '2016-11-02 23:30:45');

INSERT INTO KULLANICI_GIRIS_BILGI
VALUES (4, 'A', 'A', 'A', 'A', NULL, 1, '2016-11-04 16:55:16');

INSERT INTO KULLANICI_GIRIS_BILGI
VALUES (5, 'C', 'C', 'C', 'C', NULL, 1, '2016-11-04 16:55:32');

INSERT INTO KULLANICI_GIRIS_BILGI
VALUES (2, 'ACTIVE DIRECTORY', 'as6d54', '654sad', 'a65sd4', NULL, 1, '2016-11-08 23:52:37');

COMMIT WORK;

/* Data for the `LISANS` table  (Records 1 - 2) */

INSERT INTO LISANS
VALUES (2, 'ÝÞLETÝM SÝSTEMÝ', '2016-11-01', NULL, 'WINDOWS 7', 3, '2016-11-12 03:12:31');

INSERT INTO LISANS
VALUES (1, 'ÝÞLETÝM SÝSTEMÝ', '2016-11-01', NULL, 'WINDOWS 8.1 PRO', 3, '2016-11-12 03:15:44');

COMMIT WORK;

/* Data for the `LISANS_BILGI` table  (Records 1 - 1) */

INSERT INTO LISANS_BILGI
VALUES (4, 'ÜRÜN ANAHTARI', 'A54D6SA4D6Q5W46QW45', NULL, NULL, 2, '2016-11-12 03:25:00', NULL);

COMMIT WORK;

/* Data for the `ENVANTER_BILGI_BOS_ID` table  (Records 1 - 1) */

INSERT INTO ENVANTER_BILGI_BOS_ID
VALUES (1);

COMMIT WORK;

/* Data for the `KULLANICI_BILGI_BOS_ID` table  (Records 1 - 3) */

INSERT INTO KULLANICI_BILGI_BOS_ID
VALUES (6);

INSERT INTO KULLANICI_BILGI_BOS_ID
VALUES (6);

INSERT INTO KULLANICI_BILGI_BOS_ID
VALUES (4);

COMMIT WORK;

/* Data for the `KULLANICI_BOS_ID` table  (Records 1 - 1) */

INSERT INTO KULLANICI_BOS_ID
VALUES (5);

COMMIT WORK;

/* Data for the `LISANS_BILGI_BOS_ID` table  (Records 1 - 3) */

INSERT INTO LISANS_BILGI_BOS_ID
VALUES (1);

INSERT INTO LISANS_BILGI_BOS_ID
VALUES (2);

INSERT INTO LISANS_BILGI_BOS_ID
VALUES (3);

COMMIT WORK;

