CREATE TABLE ENVANTER 
(
  ID                         BIGINT         NOT NULL,
  "NO"                      VARCHAR(    20) NOT NULL,
  TIPI                      VARCHAR(    20) NOT NULL,
  ACIKLAMA                  VARCHAR(   200),
  YERI                      VARCHAR(    50),
  KAYIT_TARIHI                 DATE         NOT NULL,
 CONSTRAINT PK_ENVANTER PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_ENVANTER ON ENVANTER (ID);

CREATE TABLE ENVANTER_BILGI 
(
  ID                         BIGINT         NOT NULL,
  "NO"                      VARCHAR(    20) NOT NULL,
  BILGI                     VARCHAR(   200) NOT NULL,
  DEGER1                    VARCHAR(   200) NOT NULL,
  DEGER2                    VARCHAR(   200),
  DEGER3                    VARCHAR(   200),
  ENVANTER_ID                BIGINT         NOT NULL,
  KAYIT_TARIHI                 DATE         NOT NULL,
 CONSTRAINT PK_ENVANTER_BILGI PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_ENVANTER_BILGI ON ENVANTER_BILGI (ID);

CREATE TABLE ENVANTER_GIRIS_BILGI 
(
  ID                          BIGINT         NOT NULL,
  "NO"                       VARCHAR(    20) NOT NULL,
  TIPI                       VARCHAR(    50) NOT NULL,
  KULLANICI_ADI              VARCHAR(    50),
  SIFRE                       BIGINT,
  ACIKLAMA                   VARCHAR(   200),
  KAYIT_TARIHI                  DATE         NOT NULL,
  ENVANTER_ID                 BIGINT         NOT NULL,
 CONSTRAINT PK_ENVANTER_GIRIS_BILGI PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_ENVANTER_GIRIS_BILGI ON ENVANTER_GIRIS_BILGI (ID);

CREATE TABLE KULLANICI 
(
  ID                           BIGINT         NOT NULL,
  "NO"                        VARCHAR(    20) NOT NULL,
  ADI                         VARCHAR(    50) NOT NULL,
  SOYADI                      VARCHAR(    50) NOT NULL,
  BIRIM                       VARCHAR(    20),
  TELEFON_DAHILI              VARCHAR(    20),
  TELEFON_GSM                 VARCHAR(    20),
  KAYIT_TARIHI                   DATE         DEFAULT 'NOW' NOT NULL,
 CONSTRAINT PK_KULLANICI PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_KULLANICI_1 ON KULLANICI (ADI, SOYADI);
CREATE ASC INDEX INDEX_KULLANICI_0 ON KULLANICI (ID);

CREATE TABLE KULLANICI_BILGI 
(
  ID                         BIGINT         NOT NULL,
  "NO"                      VARCHAR(    20) NOT NULL,
  BILGI                     VARCHAR(   200) NOT NULL,
  DEGER1                    VARCHAR(   200) NOT NULL,
  DEGER2                    VARCHAR(   200),
  DEGER3                    VARCHAR(   200),
  KULLANICI_ID               BIGINT         NOT NULL,
  KAYIT_TARIHI                 DATE         NOT NULL,
 CONSTRAINT PK_KULLANICI_BILGI PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_KULLANICI_BILGI ON KULLANICI_BILGI (ID);

CREATE TABLE KULLANICI_ENVANTER 
(
  ID                         BIGINT         NOT NULL,
  "NO"                      VARCHAR(    20) NOT NULL,
  KULLANICI_ID               BIGINT         NOT NULL,
  ENVANTER_ID                BIGINT         NOT NULL,
  KAYIT_TARIHI                 DATE         NOT NULL,
 CONSTRAINT PK_KULLANICI_ENVANTER PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_KULLANICI_ENVANTER ON KULLANICI_ENVANTER (ID);

CREATE TABLE KULLANICI_GIRIS_BILGI 
(
  ID                          BIGINT         NOT NULL,
  "NO"                       VARCHAR(    20) NOT NULL,
  TIPI                       VARCHAR(    50),
  KULLANICI_ADI              VARCHAR(    50) NOT NULL,
  SIFRE                      VARCHAR(    50) NOT NULL,
  ACIKLAMA                   VARCHAR(   200),
  ENVANTER_ID                 BIGINT,
  KULLANICI_ID                BIGINT         NOT NULL,
  KAYIT_TARIHI                  DATE         NOT NULL,
 CONSTRAINT PK_KULLANICI_GIRIS_BILGI PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_KULLANICI_GIRIS_BILGI ON KULLANICI_GIRIS_BILGI (ID);

CREATE TABLE LISANS 
(
  ID                             BIGINT         NOT NULL,
  "NO"                          VARCHAR(    20) NOT NULL,
  TIPI                          VARCHAR(    20) NOT NULL,
  ANAHTAR                       VARCHAR(   200) NOT NULL,
  BASLANGIC_TARIHI                 DATE,
  BITIS_TARIHI                     DATE,
  ACIKLAMA                      VARCHAR(   200),
  ENVANTER_ID                    BIGINT         NOT NULL,
  KAYIT_TARIHI                     DATE         NOT NULL,
 CONSTRAINT PK_LISANS PRIMARY KEY (ID)
);
CREATE ASC INDEX INDEX_LISANS ON LISANS (ID);

CREATE OR ALTER VIEW ENVANTER_TIPLERI
(
 ENVANTER_TIPLERI 
) AS 
SELECT DISTINCT(TIPI) FROM ENVANTER

;
CREATE OR ALTER VIEW LISANS_TIPLERI
(
 LISANS_TIPLERI 
) AS 
SELECT DISTINCT(TIPI) FROM LISANS

;
ALTER TABLE KULLANICI_ENVANTER ADD CONSTRAINT FK_KULLANICI_ENVANTER 
  FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER
  (ID) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION
;

ALTER TABLE KULLANICI_ENVANTER ADD CONSTRAINT FK_KULLANICI_KULLANICI 
  FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICI
  (ID) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION
;

ALTER TABLE LISANS ADD CONSTRAINT FK_LISANS_ENVANTER 
  FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER
  (ID) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION
;

ALTER TABLE ENVANTER_GIRIS_BILGI ADD CONSTRAINT FK_ENVANTER_GIRIS_BILGI 
  FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER
  (ID) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION
;

ALTER TABLE KULLANICI_GIRIS_BILGI ADD CONSTRAINT FK_KULLANICI_GIRIS_BILGI 
  FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICI
  (ID) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION
;

ALTER TABLE ENVANTER_BILGI ADD CONSTRAINT FK_ENVANTER_BILGI 
  FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER
  (ID) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION
;

ALTER TABLE KULLANICI_GIRIS_BILGI ADD CONSTRAINT FK_KULLANICI_GIRIS_ENVANTER 
  FOREIGN KEY (ENVANTER_ID) REFERENCES ENVANTER
  (ID) 
  ON DELETE NO ACTION
  ON UPDATE NO ACTION
;

ALTER TABLE KULLANICI_BILGI ADD CONSTRAINT FK_KULLANICI_BILGI 
  FOREIGN KEY (KULLANICI_ID) REFERENCES KULLANICI
  (ID) 
  ON DELETE CASCADE
  ON UPDATE NO ACTION
;

